enb/enb-bem-techs

README.md
techs/merge-deps.js
test/techs/merge-deps.test.js

Added support of BEMDECL for `deps-merge` tech

---

techs/merge-bemdecl.js
techs/merge-deps.js
test/techs/merge-bemdecl.test.js
test/techs/merge-deps.test.js

Fixed cache for merge techs

---

techs/deps-by-tech-to-bemdecl.js
test/techs/deps-by-tech-to-bemdecl.test.js

Fixed cache for `deps-by-tech-to-bemdecl` tech

---

techs/merge-bemdecl.js
techs/merge-deps.js
test/techs/merge-bemdecl.test.js
test/techs/merge-deps.test.js

Fixed bug with merge if not result file

---

techs/levels-to-bemdecl.js
test/techs/levels-to-bemdecl.test.js

Fixed `levels-to-bemdecl` tech: should set vals for boolean mods

---

.travis.yml
appveyor.yml

Run tests in `node@0.12` and `io.js`

---

techs/deps-old.js
techs/deps.js
techs/files.js
techs/merge-deps.js
techs/subtract-deps.js
test/techs/deps-old.test.js
test/techs/deps.test.js
test/techs/files.test.js
test/techs/merge-deps.test.js
test/techs/subtract-deps.test.js

Added support for deps as array

---

.travis.yml

Speed up builds by using Docker-based Travis CI

---

appveyor.yml

Appveyor: freeze node version to 0.12

---

.travis.yml
package.json
test/mocha.opts

Travis: run coverage once

---

lib/deps/deps.js
test/techs/merge-bemdecl.test.js
test/unit/deps.test.js

Added support for mods without vals

---

exlib/deps-old.js
lib/deps/deps-graph.js
package.json
techs/deps-old.js
test/techs/deps-old.test.js
test/techs/deps-vs-deps-old-correctness-property.test.js
test/techs/deps.test.js

Currently deps-old can't guarantee correct order of deps for some cases even with no curcular `mustDeps` dependencies.
Check out this example: https://nda.ya.ru/3QXVAS

Fix deps resolving with deps-old

---

test/techs/bemjson-to-bemdecl.test.js
test/techs/deps-by-tech-to-bemdecl.test.js
test/techs/deps-old.test.js
test/techs/deps-vs-deps-old-correctness-property.test.js
test/techs/deps.test.js
test/techs/files.test.js
test/techs/levels-to-bemdecl.test.js
test/techs/levels.test.js
test/techs/merge-bemdecl.test.js
test/techs/merge-deps.test.js
test/techs/provide-bemdecl.test.js
test/techs/provide-deps.test.js
test/techs/subtract-deps.test.js

Mocha: used promises instead of callbacks

---

exlib/deps-old.js
lib/deps/deps-resolver.js
test/techs/deps-old.test.js
test/techs/deps.test.js

Fixed bug with support elem as array in deps

---

lib/deps/deps-resolver.js
test/techs/deps-old.test.js
test/techs/deps.test.js

Fixed bug with respect context in deps for elem mod

---

lib/deps/deps-resolver.js
test/techs/deps-old.test.js
test/techs/deps.test.js

Fixed bug with boolean mods as array in deps

---

exlib/deps-old.js
techs/deps-old.js
test/techs/deps-old.test.js

deps-old: warn if circular mustDeps in non-strict mode

---

techs/subtract-deps.js

subtract-deps: fixed bug with `?` in include options

---

README.md

Fixed docs for `provideDeps` tech

---

exlib/deps-old.js
test/techs/deps-old.test.js

Resolved #146 
https://nda.ya.ru/3QefzR

deps-old: Fixed circular mustDeps handling

---

exlib/deps-old.js
exlib/must-deps.js

Refactored OldDeps, fixed performance

---

lib/deps/deps-resolver.js
test/techs/deps.test.js

Fixed bug with own modifier

---

techs/files.js
test/techs/files.test.js

Fixed bug with files order by levels

---

test/techs/deps-old.test.js
test/techs/deps.test.js

Resolved #118 
@blond @tadatuta  
Please review it

#118 Add tests for verify ability to use short aliases for shoudDeps notation

---

lib/deps/deps-resolver.js
test/techs/deps-by-tech-to-bemdecl.test.js
test/techs/deps-old.test.js
test/techs/deps.test.js

Fix issue which occur for empty deps.js.
Resolved #151 
@blond 
@tadatuta 
Please review it.

#151 Support empty block-name.deps.js

---

exlib/deps-old.js
exlib/must-deps.js

@blond глянь пожалуйста. Пока читал код - немного сделал небольшие изменения по стилю. Возможно будут полезны.

Minor style fixes for deps-old

---

techs/bemdecl-from-bemjson.js
techs/bemdecl-from-deps-by-tech.js
techs/bemdecl-merge.js
techs/bemdecl-provider.js
techs/bemjson-to-bemdecl.js
techs/deps-merge.js
techs/deps-old.js
techs/deps-provider.js
techs/deps-subtract.js
techs/deps.js
techs/files.js
techs/merge-bemdecl.js
techs/merge-deps.js
techs/provide-bemdecl.js
techs/provide-deps.js
techs/subtract-deps.js

Announce for Deprecated

---

lib/deps/deps-resolver.js
lib/deps/deps.js
lib/levels/level-builder.js
lib/levels/level-plain.js
lib/levels/level.js
lib/levels/levels.js
techs/bemdecl-from-bemjson.js
techs/bemdecl-from-deps-by-tech.js
techs/bemdecl-merge.js
techs/bemdecl-provider.js
techs/bemjson-to-bemdecl.js
techs/deps-by-tech-to-bemdecl.js
techs/deps-merge.js
techs/deps-old.js
techs/deps-provider.js
techs/deps-subtract.js
techs/deps.js
techs/files.js
techs/levels-to-bemdecl.js
techs/levels.js
techs/merge-bemdecl.js
techs/merge-deps.js
techs/provide-bemdecl.js
techs/provide-deps.js
techs/subtract-deps.js

Actualized jsdoc

---

techs/files.js
test/techs/files.test.js

Fixed bug with duplicate files in nested levels

---

package.json
techs/bemjson-to-bemdecl.js
techs/deps-by-tech-to-bemdecl.js
techs/deps-old.js
techs/deps.js
techs/files.js
techs/levels-to-bemdecl.js
techs/levels.js
techs/merge-bemdecl.js
techs/merge-deps.js
techs/provide-bemdecl.js
techs/provide-deps.js
techs/subtract-deps.js

Support ENB 1.x

---

techs/deps-by-tech-to-bemdecl.js
test/techs/deps-by-tech-to-bemdecl.test.js

Fixed bug with boolean mods for depsByTech

---

techs/deps-by-tech-to-bemdecl.js
test/techs/deps-by-tech-to-bemdecl.test.js

Fixed bug with context for depsByTech

---

docs/api.ru.md
techs/bemjson-to-bemdecl.js
techs/deps-by-tech-to-bemdecl.js
techs/levels-to-bemdecl.js
test/techs/bemjson-to-bemdecl.test.js
test/techs/deps-by-tech-to-bemdecl.test.js
test/techs/levels-to-bemdecl.test.js

Added `bemdeclFormat` option

---

techs/deps-by-tech-to-bemdecl.js
test/techs/deps-by-tech-to-bemdecl.test.js

Fixed bug with extra context for depsByTech

---

techs/bemjson-to-bemdecl.js
techs/deps-by-tech-to-bemdecl.js
techs/deps-old.js
techs/deps.js
techs/files.js
techs/levels-to-bemdecl.js
techs/merge-bemdecl.js
techs/merge-deps.js
techs/provide-bemdecl.js
techs/provide-deps.js
techs/subtract-deps.js

Remove deprecated options

---

.travis.yml
appveyor.yml
package.json
test/generated/deps/deps-vs-deps-old.test.js
test/techs/bemjson-to-bemdecl.test.js
test/techs/deps-by-tech-to-bemdecl.test.js
test/techs/deps-old.test.js
test/techs/deps.test.js
test/techs/files.test.js
test/techs/levels-to-bemdecl.test.js
test/techs/levels.test.js
test/techs/merge-bemdecl.test.js
test/techs/merge-deps.test.js
test/techs/provide-bemdecl.test.js
test/techs/provide-deps.test.js
test/techs/subtract-deps.test.js
test/utils/async-require.js
test/utils/techs.js

Support Node.js 4

---

docs/build-page.md

Updated tutorials to explicitly export BEMJSON [issue 403]

---

package.json
techs/deps.js
test/techs/deps.test.js

change deps to bem-deps

---

techs/levels-to-bemdecl.js

fix(levels-to-bemdecl): should rebuild if levels was changed

---

techs/levels.js
test/techs/levels.test.js

fix(levels): support constructor block
